// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/golang-learning/inventory/internal/data/ent/schema"
	"github.com/golang-learning/inventory/internal/data/ent/storage"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	storageFields := schema.Storage{}.Fields()
	_ = storageFields
	// storageDescHostname is the schema descriptor for hostname field.
	storageDescHostname := storageFields[0].Descriptor()
	// storage.HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	storage.HostnameValidator = storageDescHostname.Validators[0].(func(string) error)
	// storageDescSize is the schema descriptor for size field.
	storageDescSize := storageFields[1].Descriptor()
	// storage.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	storage.SizeValidator = storageDescSize.Validators[0].(func(int) error)
}
